const selectionRouter = {
  route: null,
  name: null,
  title: '选品系统',
  type: 'folder',
  icon: 'iconfont icon-shangpinguanli',
  filePath: 'view/selection/',
  order: null,
  inNav: true,
  children: [
    {
      title: 'BI监控',
      type: 'view',
      name: 'SelectionDashboard',
      route: '/selection/dashboard',
      filePath: 'view/selection/dashboard/index.vue',
      inNav: true,
      icon: 'iconfont icon-jiemiansheji',
    },
    {
      title: '产品管理',
      type: 'view',
      name: 'ProductList',
      route: '/selection/products',
      filePath: 'view/selection/product/product-list.vue',
      inNav: true,
      icon: 'iconfont icon-shangpinguanli',
    },
    {
      title: '产品详情',
      type: 'view',
      name: 'ProductDetail',
      route: '/selection/product/:id',
      filePath: 'view/selection/product/product-detail.vue',
      inNav: false,
      icon: 'iconfont icon-shangpinguanli',
    },
    {
      title: '策略中心',
      type: 'view',
      name: 'StrategyCenter',
      route: '/selection/strategies',
      filePath: 'view/selection/strategy/strategy-center.vue',
      inNav: true,
      icon: 'iconfont icon-fenxi',
    },
    {
      title: '40题自诊',
      type: 'view',
      name: 'StrategyDiagnosis',
      route: '/selection/strategy/diagnosis',
      filePath: 'view/selection/strategy/diagnosis.vue',
      inNav: false,
    },
    {
      title: '四层评估',
      type: 'view',
      name: 'StrategyEvaluation',
      route: '/selection/strategy/evaluation',
      filePath: 'view/selection/strategy/evaluation.vue',
      inNav: false,
    },
    {
      title: '利润模型',
      type: 'view',
      name: 'StrategyProfit',
      route: '/selection/strategy/profit',
      filePath: 'view/selection/strategy/profit.vue',
      inNav: false,
    },
    {
      title: '风险预警',
      type: 'view',
      name: 'StrategyRisk',
      route: '/selection/strategy/risk',
      filePath: 'view/selection/strategy/risk.vue',
      inNav: false,
    },
    {
      title: 'TOP20策略',
      type: 'view',
      name: 'StrategyTop20',
      route: '/selection/strategy/top20',
      filePath: 'view/selection/strategy/top20.vue',
      inNav: false,
    },
    {
      title: '蓝海识别',
      type: 'view',
      name: 'StrategyBlueOcean',
      route: '/selection/strategy/blue-ocean',
      filePath: 'view/selection/strategy/blue-ocean.vue',
      inNav: false,
    },
    {
      title: '爆点识别',
      type: 'view',
      name: 'StrategyExplosive',
      route: '/selection/strategy/explosive',
      filePath: 'view/selection/strategy/explosive.vue',
      inNav: false,
    },
    {
      title: '创新矩阵',
      type: 'view',
      name: 'StrategyInnovation',
      route: '/selection/strategy/innovation',
      filePath: 'view/selection/strategy/innovation.vue',
      inNav: false,
    },
    {
      title: '评分策略',
      type: 'view',
      name: 'StrategyGeneric',
      route: '/selection/strategy/scoring',
      filePath: 'view/selection/strategy/generic-scoring.vue',
      inNav: false,
    },
    {
      title: '决策树',
      type: 'view',
      name: 'StrategyDecisionTree',
      route: '/selection/strategy/decision-tree',
      filePath: 'view/selection/strategy/decision-tree.vue',
      inNav: false,
    },
    {
      title: '竞品分析',
      type: 'view',
      name: 'StrategyCompetitor',
      route: '/selection/strategy/competitor',
      filePath: 'view/selection/strategy/competitor-analysis.vue',
      inNav: false,
    },
    {
      title: '多产品对比',
      type: 'view',
      name: 'ProductComparison',
      route: '/selection/comparison',
      filePath: 'view/selection/product/comparison.vue',
      inNav: true,
      icon: 'iconfont icon-fuzhi',
    },
    {
      title: '审批流程',
      type: 'view',
      name: 'ApprovalList',
      route: '/selection/approvals',
      filePath: 'view/selection/product/approval.vue',
      inNav: true,
      icon: 'iconfont icon-naozhongxiaoxitixing',
    },
    {
      title: '系统设置',
      type: 'view',
      name: 'SelectionSettings',
      route: '/selection/settings',
      filePath: 'view/selection/setting/index.vue',
      inNav: true,
      icon: 'iconfont icon-shangpinguanli',
    },
    {
      title: 'SOP执行',
      type: 'view',
      name: 'SopExecution',
      route: '/selection/product/:id/sop',
      filePath: 'view/selection/product/sop.vue',
      inNav: false,
    },
    {
      title: '历史趋势',
      type: 'view',
      name: 'ProductTrends',
      route: '/selection/product/:id/trends',
      filePath: 'view/selection/product/trends.vue',
      inNav: false,
    },
    {
      title: '检查清单',
      type: 'view',
      name: 'ProductChecklist',
      route: '/selection/product/:id/checklist',
      filePath: 'view/selection/product/checklist.vue',
      inNav: false,
    },
    {
      title: '压力测试',
      type: 'view',
      name: 'StressTest',
      route: '/selection/strategy/stress-test',
      filePath: 'view/selection/strategy/stress-test.vue',
      inNav: false,
    },
    {
        title: '企业定位',
        type: 'view',
        name: 'EnterpriseProfile',
        route: '/selection/enterprise',
        filePath: 'view/selection/enterprise/index.vue',
        inNav: true,
        icon: 'iconfont icon-gongsiguanli',
    }
  ],
}

export default selectionRouter
